

services:
  mysql:
    container_name: urls
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: urls
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-demo

  app:
    container_name: urlshortner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/urls?createDatabaseIfNotExists=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
      SERVER_SERVLET_CONTEXT_PATH: /url/shorter
    depends_on:
      - mysql
    networks:
      - spring-demo

  spring-api:
    container_name: spring-api
    image: url-shortner-fullstack-app
    ports:
      - "8080:8080"
    environment:
      SERVER_SERVLET_CONTEXT_PATH: /url/shorter
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/urls?createDatabaseIfNotExists=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    networks:
      - spring-demo
    depends_on:
      - mysql

  front:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - url-shortner-fullstack-app/app:latest
    image: url-shortner-fullstack-app/front:latest
    ports:
      - "8082:80"
    depends_on:
      - spring-api
    networks:
      - spring-demo
    environment:
      - NODE_ENV=production
      - PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    restart: unless-stopped


    # Changed from ro to rw


networks:
  spring-demo:
    driver: bridge

x-build-args:
  NGINX_CONF_PATH: /etc/nginx/nginx.conf

volumes:
  mysql-data:
    driver: local
