

services:
  mysql:
    container_name: urls
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: urls
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-demo

  app:
    container_name: urlshortner
    build:
      context: ./urlshortner
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/urls?createDatabaseIfNotExists=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_MVC_CORS_ALLOWED-ORIGINS: http://localhost:8081,http://localhost:8080,http://localhost:4200,http://3.23.114.107,http://3.23.114.107:8081
    depends_on:
      - mysql
    networks:
      - spring-demo


  front:
    container_name: front
    image: url-shortner-fullstack-app/front
    build:
      context: ./urlfront
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - spring-demo
    volumes:
      - ./urlfront/nginx.conf:/etc/nginx/nginx.conf

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-data:
    driver: local
