version: '3.8'
services:
  mysql:
    container_name: urls
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: urls
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-demo

  app:
    container_name: urlshortner
    build:
      context: .
      dockerfile: Dockerfile # Adjust this path if necessary
    ports:
      - "3636:3636"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/urls?createDatabaseIfNotExists=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - mysql
    networks:
      - spring-demo

  spring-api:
    container_name: spring-api
    image: url-shortner-fullstack-app # Ensure this matches the image name exactly
    ports:
      - "8080:8080" # Adjust the host port if 8080 is already in use
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-data:
    driver: local
